import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/providers/query-client-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <main className="min-h-screen  bg-[#BEF7F7]">
            <div className="wrapper">{children}</div>
          </main>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
